import { InventoryLocation } from '../types/inventory';

export const mockInventory: InventoryLocation[] = [
  {
    id: 'inv-tpe-101',
    name: 'Taipei 101 Mega Screen',
    city: 'Taipei',
    district: 'Xinyi',
    address: 'No. 7, Section 5, Xinyi Rd, Xinyi District, Taipei City',
    latitude: 25.033964,
    longitude: 121.564468,
    venueType: 'Mall',
    screenType: 'Mega Screen',
    dailyImpressions: 850000,
    pricePerDay: 15000,
    cpm: 17.65,
    availability: 0.8,
    audienceTags: ['Tourists', 'Shoppers', 'Professionals'],
    imageUrl: '/images/tpe_101.png',
    description: 'Iconic mega screen located at the base of Taipei 101, capturing immense foot traffic from both tourists and local shoppers.',
  },
  {
    id: 'inv-tpe-main',
    name: 'Taipei Main Station Hall',
    city: 'Taipei',
    district: 'Zhongzheng',
    address: 'No. 3, Beiping W Rd, Zhongzheng District, Taipei City',
    latitude: 25.047908,
    longitude: 121.517315,
    venueType: 'Station',
    screenType: 'Indoor',
    dailyImpressions: 1200000,
    pricePerDay: 18000,
    cpm: 15.00,
    availability: 0.9,
    audienceTags: ['Commuters', 'Tourists', 'Students'],
    imageUrl: '/images/tpe_main_station.png',
    description: 'Central transport hub of Taipei. The main hall screens reach millions of daily commuters and inter-city travelers.',
  },
  {
    id: 'inv-tpe-sogo',
    name: 'Zhongxiao Fuxing SOGO Intersection',
    city: 'Taipei',
    district: 'Da\'an',
    address: 'Intersection of Zhongxiao E Rd and Fuxing S Rd',
    latitude: 25.0416,
    longitude: 121.5438,
    venueType: 'Street',
    screenType: 'Billboard',
    dailyImpressions: 600000,
    pricePerDay: 12000,
    cpm: 20.00,
    availability: 0.5,
    audienceTags: ['Shoppers', 'Professionals'],
    imageUrl: '/images/tpe_sogo.png',
    description: 'Premium intersection connecting major shopping districts, capturing high-end shoppers and young professionals.',
  },
  {
    id: 'inv-tpe-ximen',
    name: 'Ximending 6 Exit Billboard',
    city: 'Taipei',
    district: 'Wanhua',
    address: 'Exit 6, Ximen MRT Station, Chengdu Rd',
    latitude: 25.0422,
    longitude: 121.5083,
    venueType: 'Street',
    screenType: 'Mega Screen',
    dailyImpressions: 950000,
    pricePerDay: 14000,
    cpm: 14.74,
    availability: 0.7,
    audienceTags: ['Students', 'Tourists', 'Shoppers'],
    imageUrl: '/images/tpe_ximen.png',
    description: 'The "Shibuya of Taipei". This screen dominates the main plaza where youth and pop culture converge.',
  },
  {
    id: 'inv-tpe-nangang',
    name: 'Nangang Software Park Display',
    city: 'Taipei',
    district: 'Nangang',
    address: 'No. 19-2, Sanchong Rd, Nangang District',
    latitude: 25.0594,
    longitude: 121.6111,
    venueType: 'Office Building',
    screenType: 'Kiosk',
    dailyImpressions: 250000,
    pricePerDay: 4000,
    cpm: 16.00,
    availability: 0.95,
    audienceTags: ['Tech Workers', 'Professionals', 'Commuters'],
    imageUrl: '/images/tpe_nangang.png',
    description: 'Targeted placement within the heart of Taipei\'s tech hub, reaching high-income tech professionals.',
  },
  {
    id: 'inv-tpe-songshan',
    name: 'Songshan Airport Arrival Hall',
    city: 'Taipei',
    district: 'Songshan',
    address: 'No. 340-9, Dunhua N Rd, Songshan District',
    latitude: 25.0622,
    longitude: 121.5517,
    venueType: 'Airport',
    screenType: 'Indoor',
    dailyImpressions: 150000,
    pricePerDay: 6000,
    cpm: 40.00,
    availability: 0.4,
    audienceTags: ['Tourists', 'Professionals'],
    imageUrl: '/images/tpe_songshan.png',
    description: 'High CPM placement targeting international and domestic business travelers directly at the arrival gates.',
  },
  {
    id: 'inv-ntpc-banqiao',
    name: 'Banqiao Station Transfer Corridor',
    city: 'New Taipei',
    district: 'Banqiao',
    address: 'No. 7, Section 2, Xianmin Blvd, Banqiao District',
    latitude: 25.0143,
    longitude: 121.4635,
    venueType: 'Station',
    screenType: 'Transit',
    dailyImpressions: 700000,
    pricePerDay: 9000,
    cpm: 12.86,
    availability: 0.85,
    audienceTags: ['Commuters', 'Shoppers', 'Students'],
    imageUrl: '/images/ntpc_banqiao.png',
    description: 'Major transit hub in New Taipei connecting HSR, TRA, and MRT lines, ensuring massive daily reach.',
  },
  {
    id: 'inv-tpe-neihu',
    name: 'Neihu Tech Park Ruiguang Rd',
    city: 'Taipei',
    district: 'Neihu',
    address: 'Intersection of Ruiguang Rd and Gangqian Rd',
    latitude: 25.0784,
    longitude: 121.5753,
    venueType: 'Street',
    screenType: 'Billboard',
    dailyImpressions: 400000,
    pricePerDay: 7500,
    cpm: 18.75,
    availability: 0.6,
    audienceTags: ['Tech Workers', 'Professionals'],
    imageUrl: '/images/tpe_neihu.png',
    description: 'Roadside billboard targeting the daily commute of tech industry workers driving into Neihu Technology Park.',
  },
  {
    id: 'inv-tpe-shilin',
    name: 'Shilin Night Market Entrance',
    city: 'Taipei',
    district: 'Shilin',
    address: 'Intersection of Jihe Rd and Wenlin Rd',
    latitude: 25.0880,
    longitude: 121.5248,
    venueType: 'Night Market',
    screenType: 'Street Furniture',
    dailyImpressions: 450000,
    pricePerDay: 5000,
    cpm: 11.11,
    availability: 0.9,
    audienceTags: ['Foodies', 'Tourists', 'Students'],
    imageUrl: '/images/tpe_shilin.png',
    description: 'High visibility screen at the entrance of Taiwan\'s most famous night market, excellent for FMCG brands.',
  },
  {
    id: 'inv-tpe-gongguan',
    name: 'Gongguan Roosevelt Rd Intersection',
    city: 'Taipei',
    district: 'Zhongzheng',
    address: 'Section 4, Roosevelt Rd',
    latitude: 25.0152,
    longitude: 121.5342,
    venueType: 'Street',
    screenType: 'Billboard',
    dailyImpressions: 300000,
    pricePerDay: 4500,
    cpm: 15.00,
    availability: 0.75,
    audienceTags: ['Students', 'Foodies'],
    imageUrl: '/images/tpe_gongguan.png',
    description: 'Located right outside National Taiwan University, the perfect location for targeting Gen Z and young adults.',
  }
];
